### ISSUE TITLE
Use coap pings instead of get request

### ISSUE THREAD

**Issue by AlCalzone** [hemtjanst/tradfri-mqtt#1]
Pinging the remote endpoint can be simplified starting with node-coap-client v0.3:
https://github.com/AlCalzone/node-coap-client/#ping-a-coap-origin
```
const success: boolean = await coap.ping(...);
```
Also, that method uses inexpensive [CoAP pings](https://tools.ietf.org/html/rfc7252#section-4.3) instead of a full-blown request.

**Comment by bonan** [comment]
Thanks

Do you know if the ping request can be used to detect if the DTLS session has died?

The issue I'm having is that the gateway either stops responding completely, or that the DTLS session expires and I have to renegotiate a new session.

**Comment by AlCalzone** [comment]
Basically this should be detectable on the DTLS layer. My implementation is by no means complete, so it might be that the client is missing a renegotiation request or something like that. Currently, I'm checking on the application layer if a couple of consecutive pings have failed (which _can_ mean that the session is failed) and then reset the CoAP client.

**Comment by bonan** [comment]
`coap.ping()` is now being used since 4de7687
