### ISSUE TITLE
The DTLS handshake timeout error returned

### ISSUE THREAD

**Issue by Arnootjoo** [hemtjanst/tradfri-mqtt#17]
See reaction of @olem10 in last closed issue. The fix in the last build worked for me, but this error shows again since the last Tradfri update:. Hub software version is 1.15.55. Hope there's a fix for this.

_Error discovering Trådfri endpoints Error: The DTLS handshake timed out
    at normalizeReason (/app/node_modules/node-coap-client/build/lib/DeferredPromise.js:6:16)
    at Promise.rej [as reject] (/app/node_modules/node-coap-client/build/lib/DeferredPromise.js:14:34)
    at Socket.onError (/app/node_modules/node-coap-client/build/CoapClient.js:1012:29)
    at Object.onceWrapper (node:events:514:26)
    at Socket.emit (node:events:394:28)
    at Socket.killConnection (/app/node_modules/node-dtls-client/build/dtls.js:227:22)
    at Socket.expectHandshake (/app/node_modules/node-dtls-client/build/dtls.js:144:22)
    at Timeout.<anonymous> (/app/node_modules/node-dtls-client/build/dtls.js:102:61)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)_

_Originally posted by @Arnootjoo in https://github.com/hemtjanst/tradfri-mqtt/issues/15#issuecomment-915066414_

**Comment by daenney** [comment]
The IKEA release notes are tremendously helpful :roll_eyes: 

> Release Version: 1.17.1
3rd Aug 2021
New features and changes in Gateway: 1.15.55

> Maintenance and bug fixes
Fix for Gateway Zigbee network info change where all devices went into ‘unreachable’ state for some people

> New features and changes in Accessories:

> Support for STARKVIND Air Purifier (V-1.0.033)
New Product.

According to the release notes, this gateway version got pushed in the 3rd of August. If the errors have only started to show up now that would suggest the error is not related to the firmware update. Did you do the update today?

**Comment by olem10** [comment]
My problem occurred with the 30th June update. In the release notes a CoAP bug fix is mentioned.

Release Version: 1.17.0
30th June 2021
New features and changes in Gateway: 1.15.34
Apple HomeKit Upgrade from ADK2.1 to ADK5.0
Support for Battery % for Shortcut button & Motion Sensor in Apple Homekit
Bug fixes – Motion sensor support in AHK, CoAP issues

I have later on tried to connect to the Gateway using the Java-based ikea-tradfri-api (https://github.com/StijnGroenen/ikea-tradfri-api). This uses the Californium CoAP framework and works perfectly.

**Comment by olem10** [comment]
I looked closer into the packages installed on my raspberry pi. It turned out that npm did not reflect the package updates of the coap and dtls client. Uninstalling and reinstalling tradfri-mqtt solved my problem. Everything seems to be working ok, I am able to connect to the gateway and receive mqtt updates.

**Comment by daenney** [comment]
That's good to hear! Thanks for circling back on this and letting us know.
