### ISSUE TITLE
Possibility to control (activate) scenes?

### ISSUE THREAD

**Issue by RedNoteFanatic** [hemtjanst/tradfri-mqtt#18]
Is there a possibility to activate the scenes created in the Tradfri app through tradfri-mqtt? 

They are under mqtt-topic "tradfri-raw/15005". I have an example from my home "tradfri-raw/15005/131073/196608". This turns off all lighting in one room (group).

**Comment by bonan** [comment]
It should be possible to send something like this:

```
{
  "method": "put",
  "url": "15005/131073",
  "payload": {
    "5850": 1,
    "9039": 196608
  }
}
```

**Comment by RedNoteFanatic** [comment]
I have tried this but it doesn't give any response. I have also tried to add a reply url but no reply. 

I tried:

```
{
    "method": "put",
    "url": "15005/131073",
    "payload": {
        "5850": 1,
        "9039": 196608
    }
}
```
on topic: tradfri-cmd

**Comment by bonan** [comment]
sorry, the url should be 15004/131073, not 15005/...

**Comment by RedNoteFanatic** [comment]
And thats works. Thanks for the help.
