### ISSUE TITLE
How to control curtain?

### ISSUE THREAD

**Issue by RedNoteFanatic** [hemtjanst/tradfri-mqtt#19]
I have tried to control a curtain in a group the same way as a dimmers in a group would be controlled. But havent succeded. Is it possible?

**Comment by bonan** [comment]
I haven't used the trådfri gateway in a few years, so haven't really tested with blinds.

Looking at https://github.com/AlCalzone/node-tradfri-client/tree/master/src/lib - the magic number seems to be `5536` with range 0-100

I.e. payload `{"5536": 50}` should move the blind half-way

**Comment by RedNoteFanatic** [comment]
Ok, didnt know it was built on node-tradfri-client. Thanks.
