### ISSUE TITLE
Add topic to ENV

### ISSUE THREAD

**Issue by ruudboon** [hemtjanst/tradfri-mqtt#2]
Thank you for this project. 
I would like to change the topic (currently it's tradfri-raw) 
Would it possible to add a variable to set the topic where to publish to?
For example
MQTT_ADDRESS=tradfri

**Comment by bonan** [comment]
`MQTT_ADDRESS` is used for the mqtt URL

I added `MQTT_TOPIC_PREFIX` (instead of hard-coded `tradfri-raw`) and `MQTT_TOPIC_CMD` (instead of hard-coded `tradfri-cmd`).
