### ISSUE TITLE
Command hangs without listening on MQTT port

### ISSUE THREAD

**Issue by redfast00** [hemtjanst/tradfri-mqtt#23]
As per the README, I ran:

`npx tradfri-mqtt -g 10.0.0.9 -p PASSCODE_ON_BACK_OF_TRADFRI -a tcp://127.0.0.1:1883`

It doesn't seem to listen on any ports though (confirmed with `nmap localhost -p1883`)

**Comment by bonan** [comment]
You need to run something like [Mosquitto](https://mosquitto.org/), which will listen on port 1883.

Tradfri-mqtt will then connect to that broker

**Comment by redfast00** [comment]
:facepalm: you're completely right, I forgot. Might still be useful to print something to the console, right now it's completely silent and does not seem to timeout.
