### ISSUE TITLE
[NFR] Friendly topic and payload 

### ISSUE THREAD

**Issue by ruudboon** [hemtjanst/tradfri-mqtt#5]
Thnx for releasing v0.0.5, it works really well.
I'm wondering if I could drop a New Feature Request here.

It would be really handy if we can subscribe and publish to the same endpoint where the endpoint contains parsed attributes.

For example if I have a group called "outside" with 2 lights (garden, front door)

```
Subscribe to: /tradfri/groups/outside 
An update gives:
{
   brightness  : 0, // [0..254 ID 5851]
   state: 0 // [0/1, ID 5850]
}
```
```
Publish to: /tradfri/groups/outside
Payload:
{
   brightness  : 200,
   state: 1
}
```
```
Subscribe to: /tradfri/lights/garden 
An update gives:
{
   brightness  : 0, // [0..254 ID 5851]
   state: 0 // [0/1, ID 5850]
}
etc...
```
I found a list of attributes [here](https://github.com/ggravlingen/pytradfri/blob/0a0f6666dcd13d5c9d3150f7459fdec4f96e6150/pytradfri/const.py)
Mqtt 3.1. can handle UTF-8 characters so using names in the topic should be a problem.
One issue could be that the group or light is not unique in that case both groups or light should be triggered.

**Comment by daenney** [comment]
I think allowing for friendly names could be useful, but I disagree with the approach around name clashes. The gateway doesn't allow duplicate names within an entity, so you can't have 2 bulbs with the same name or 2 groups with the same name, but you can have a bulb and a group with the same name, but the bulb doesn't have to be in that same group.

I could easily have a bathroom downstairs with a light named bathroom and a bathroom upstairs that is controlled by a group named bathroom. Sending a command to `/bathroom` would now cause both the upstairs and downstairs bathroom to trigger. For me this isn't helpful behaviour, it's surprising behaviour and usually surprising isn't something I'd like my home automation to be. Lets say someone was using the downstrais bathroom and someone else the upstairs one. The person upstairs is now finished and sends the command to turn of the bathroom. Now all of a sudden the person downstairs finds themselves in a dark bathroom for no apparent reason.

It might be more helpful to have something along the lines of `/group/<friendly>` and `/accessory/<friendly>`. This still makes all things easily accessible by name but even in the case of name clashes makes it still possible for anyone integrating with it to be explicit about what they meant to trigger.

**Comment by bonan** [comment]
I think this is out of scope for this project, the purpose of the project is to mirror Trådfri into MQTT and let other services consume events and send commands without us having to build support for all features.

The project was only meant as a stopgap solution for [sladdlös](https://github.com/hemtjanst/sladdlos) until someone creates a coap-dtls go library with support for the Trådfri cryptos
