### ISSUE TITLE
tradfri-cmd for getting moods

### ISSUE THREAD

**Issue by blubberblah** [hemtjanst/tradfri-mqtt#6]
Hello,
thank you for this great library I just wanted to know if there is a tradfri-cmd to explicitly receive all available moods? If so, how ist the url?
Thanks in advance,
Regards

**Comment by bonan** [comment]
You don't need a command to get the moods/scenes. 

You just need to subscribe to `tradfri-raw/15005/+/+`

Example of message (at `tradfri-raw/15005/195060/229039`):
```json
{
  "9001":"FOCUS",
  "9002":1521991730,
  "9003":229039,
  "9068":1,
  "9057":2,
  "15013":[{"5850":1,"5851":254,"9003":65573}]
}
```

In the topic: 195060 is the group, 229039 is the scene id

To switch scene, send `{"9039": 229039}` to the group endpoint

**Comment by blubberblah** [comment]
Thanks for the detailed reply! Regards
