### ISSUE TITLE
oberserving all possible topics and debugging

### ISSUE THREAD

**Issue by Wuppi68** [hemtjanst/tradfri-mqtt#7]
Hi,

whats about the following changes?

a) observing all possible "topics"; you get the list when get the following url from the gateway: cmd {"method":"get","url":".well-known/core","id":"well-known","replyTopic":"ikea/response"}; publish the cmd and read the respone. For myself it Looks like this:
Format 40 --> link list
all items with obs set can be observed:
{"id":"well-known","code":"2.05","format":40,"payload":"<//15006>;ct=0;obs,<//15001>;ct=0;obs,<//15004>;ct=0;obs,<//15004/add>;ct=0,<//15004/remove>;ct=0,<//15010>;ct=0;obs,<//15005>;ct=0;obs,<//15011/15012>;ct=0;obs,<//15011/9034>;ct=0,<//15011/9030>;ct=0,<//15011/9031>;ct=0,<//15011/9102>;ct=0,<//15011/9094>;ct=0;obs,<//15011/9095>;ct=0;obs,<//15011/9104>;ct=0;obs,<//15004/161295>;ct=0;obs,<//15005/161295>;ct=0;obs,<//15005/146016/226828>;ct=0;obs,<//15005/161303/226835>;ct=0;obs,<//15005/161303/226836>;ct=0;obs,<//15005/161303/226837>;ct=0;obs,<//15004/146016>;ct=0;obs,<//15005/146016>;ct=0;obs,<//15001/65557>;ct=0;obs,<//15001/65558>;ct=0;obs,<//15001/65542>;ct=0;obs,<//15001/65538>;ct=0;obs,<//15001/65551>;ct=0;obs,<//15001/65552>;ct=0;obs,<//15001/65560>;ct=0;obs,<//15001/65540>;ct=0;obs,<//15001/65554>;ct=0;obs,<//15001/65539>;ct=0;obs,<//15001/65548>;ct=0;obs,<//15001/65537>;ct=0;obs,<//15001/65550>;ct=0;obs,<//15001/65543>;ct=0;obs,<//15001/65541>;ct=0;obs,<//15001/65549>;ct=0;obs,<//15005/161295/211896>;ct=0;obs,<//15005/161295/224865>;ct=0;obs,<//15005/161295/204477>;ct=0;obs,<//15004/161303>;ct=0;obs,<//15005/161303>;ct=0;obs,<//15005/161304/226838>;ct=0;obs,<//15005/161304/226839>;ct=0;obs,<//15005/161304/226840>;ct=0;obs,<//15004/161304>;ct=0;obs,<//15005/161304>;ct=0;obs,<//15005/146016/212837>;ct=0;obs,<//15005/146016/226810>;ct=0;obs,<//15005/146016/212663>;ct=0;obs,<//15005/146016/202403>;ct=0;obs,<//15004/161299>;ct=0;obs,<//15005/161299>;ct=0;obs,<//15005/161305/226841>;ct=0;obs,<//15005/161305/226842>;ct=0;obs,<//15005/161305/226843>;ct=0;obs,<//15004/161305>;ct=0;obs,<//15005/161305>;ct=0;obs,<//15005/161299/226822>;ct=0;obs,<//15005/161299/226823>;ct=0;obs,<//15005/161299/226824>;ct=0;obs,<//15011/9063>;ct=0,<//15005/146016/226844>;ct=0;obs,<//15010/313073>;ct=0;obs"}

b) send debug Information into topic debug?

Kind regards

Ralf

**Comment by bonan** [comment]
Since v0.1.0 the well-known URL will be queried on init and then every 5 minutes, the contents will also be published to `tradfri-raw/.well-known/core`

Sending debugging info into MQTT requires a bit more refactoring, and should be a separate issue

**Comment by Wuppi68** [comment]
thank you :-)
